version: '2'
services:
  digdag:
    build: . 
    ports:
      - "65432:65432"
      - "65433:65433"
  postgresql:
    image: postgres:9
    environment:
      - POSTGRES_USER=digdag
      - POSTGRES_PASSWORD=digdag
      - POSTGRES_DB=digdag
    command: 
     - postgres
     - -c
     - superuser_reserved_connections=30
     - -c
     - max_connections=1000

